#Requires -Version 5.1
<#
.SYNOPSIS
    One-shot installer for the "BeeSync15Min" Windows scheduled task (Layer 1).

.DESCRIPTION
    Creates a user-level scheduled task that runs bee-sync-scheduled.ps1 every
    15 minutes while you're logged in. No UAC elevation required.

    On first run, prompts for your Obsidian vault's `_raw` path (and, if this
    folder is inside a Kiro workspace, automatically detects the sentinel
    directory for the Kiro hook). Writes both to
    %LOCALAPPDATA%\bee-sync\config.ps1 so Layer 1 and Layer 2 share config.

.NOTES
    Uses schtasks.exe (not Register-ScheduledTask) for broader compatibility
    on locked-down machines.
#>

$ErrorActionPreference = 'Stop'

$taskName   = 'BeeSync15Min'
$scriptDir  = Split-Path -Parent $PSCommandPath
$syncScript = Join-Path $scriptDir 'bee-sync-scheduled.ps1'

if (-not (Test-Path $syncScript)) {
    Write-Error "Cannot find $syncScript."
    exit 1
}

# Ensure config exists
$configDir  = Join-Path $env:LOCALAPPDATA 'bee-sync'
$configFile = Join-Path $configDir 'config.ps1'
if (-not (Test-Path $configDir)) { New-Item -ItemType Directory -Force -Path $configDir | Out-Null }

if (-not (Test-Path $configFile)) {
    Write-Host ""
    Write-Host "=== First-time setup ==="
    Write-Host "Enter the full path to your Obsidian vault's Bee raw folder."
    Write-Host "Typical paths:"
    Write-Host "  C:\Users\YOUR_USERNAME\iCloud Drive\Obsidian\YOUR_VAULT\05 Reference\Bee\_raw"
    Write-Host "  C:\Users\YOUR_USERNAME\Documents\YOUR_VAULT\05 Reference\Bee\_raw"
    Write-Host ""
    $vaultPath = Read-Host "Vault _raw path"
    if ([string]::IsNullOrWhiteSpace($vaultPath)) {
        Write-Error "No path provided. Exiting."
        exit 1
    }
    if (-not (Test-Path $vaultPath)) {
        Write-Warning "Path does not exist yet: $vaultPath"
        Write-Warning "Continuing anyway -- create the folder in Obsidian before the first scheduled run."
    }

    # Auto-detect Kiro workspace root. If this installer lives at <workspace>/scripts/,
    # the workspace root is one level up. If the user is running from a Kiro-enabled
    # workspace with a .kiro folder, point sentinels at <workspace>/.kiro/bee-inbox/.
    $workspaceRoot = Split-Path -Parent $scriptDir
    $kiroWorkspaceDir = Join-Path $workspaceRoot '.kiro'
    $sentinelDir = ''
    if (Test-Path $kiroWorkspaceDir) {
        $sentinelDir = Join-Path $kiroWorkspaceDir 'bee-inbox'
        New-Item -ItemType Directory -Force -Path $sentinelDir | Out-Null
        Write-Host "Detected Kiro workspace at: $workspaceRoot"
        Write-Host "Sentinel directory: $sentinelDir"
    } else {
        Write-Host "No Kiro workspace detected (no .kiro/ folder one level up)."
        Write-Host "Sentinel-based auto-processing via Kiro hook will not work."
        Write-Host "You can still use the sync scripts -- the Kiro auto-processing just won't fire."
    }

    $configLines = @(
        "# Auto-generated by install-bee-sync-task.ps1"
        "# Edit this file to change paths; delete it to re-run the installer prompt."
        "`$VaultRaw = '$vaultPath'"
    )
    if ($sentinelDir) {
        $configLines += "`$SentinelDir = '$sentinelDir'"
    }
    Set-Content -Path $configFile -Value ($configLines -join "`r`n") -Encoding UTF8
    Write-Host "Config saved: $configFile"
}

# Remove prior registration (silent)
& schtasks.exe /Delete /TN $taskName /F *> $null

$command = 'powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "' + $syncScript + '"'
$startTime = (Get-Date).AddMinutes(1).ToString('HH:mm')

$result = & schtasks.exe /Create /TN $taskName /TR $command /SC MINUTE /MO 15 /ST $startTime /F 2>&1
Write-Host $result
Write-Host ""
Write-Host "Installed: $taskName"
Write-Host "Runs every 15 minutes."
Write-Host "Logs: $configDir\bee-sync.log"
Write-Host ""
Write-Host "Smoke test (run it now):"
Write-Host "    schtasks /Run /TN $taskName"
Write-Host ""
Write-Host "Uninstall:"
Write-Host "    schtasks /Delete /TN $taskName /F"
